# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: user123123

development:
  <<: *default
  database: rspec_demo_development

test:
  <<: *default
  database: rspec_demo_test<%= ENV['TEST_ENV_NUMBER'] %>
